Update 2024.md
mautic/hacktoberfest-no-code pull request #1
Opened 2024-09-25 12:40 UTC by favour-chibueze

2024-09-25 13:20 UTC, RCheesley commented on 2024.md
> +Welcome to **Hacktoberfest 2024**! We're excited that you're interested in contributing to **Mautic**, an open-source marketing automation platform. Contributions come in many forms, and not all of t
```suggestion
Welcome to **Hacktoberfest 2024**! We're excited that you're interested in contributing to **Mautic**, an open source marketing automation platform. Contributions come in many forms, and not all of them require coding skills. This guide will show you how to contribute to Mautic without writing a single line of code!
```

2024-09-25 13:20 UTC, RCheesley commented on 2024.md
> +[Mautic](https://www.mautic.org/) is the world’s largest open-source marketing automation project. With over 200,000 organisations using Mautic and over 1,000 community volunteers, we empower busines
```suggestion
[Mautic](https://www.mautic.org/) is the world’s largest open source marketing automation project. With over 200,000 organisations using Mautic and over 1,000 community volunteers, we empower businesses by making it easy to manage their marketing across a range of channels. 
```

2024-09-25 13:20 UTC, RCheesley commented on 2024.md
> +[Hacktoberfest](https://hacktoberfest.com/) is an annual event encouraging contributions to open-source projects. Throughout October, participants are invited to submit contributions to open-source r
```suggestion
[Hacktoberfest](https://hacktoberfest.com/) is an annual event encouraging contributions to open source projects. Throughout October, participants are invited to submit contributions to open source repositories like Mautic. Contributions can be code, documentation, design, translations, or community support.
```

2024-09-25 13:21 UTC, RCheesley commented on 2024.md
> +Open-source projects thrive not only from code contributions but also from the community's efforts in other areas. No-code contributions help Mautic grow and improve through better documentation, tra
```suggestion
Open source projects thrive not only from code contributions but also from the community's efforts in other areas. No-code contributions help Mautic grow and improve through better documentation, translations, community support, and more. If you're not a developer but want to contribute to open source, there are plenty of ways to get involved!
```

2024-09-25 13:22 UTC, RCheesley commented on 2024.md
> +   Register to participate in Mautic's Hacktoberfest event by filling out the form here: [Mautic Hacktoberfest 2024 Signup](https://m.mautic.org/hacktoberfest-24-signup). Please     indicate **how yo
```suggestion
   Register to participate in Mautic's Hacktoberfest event by filling out the form here: [Mautic Hacktoberfest 2024 Signup](https://m.mautic.org/hacktoberfest-24-signup). Please indicate **how you'd like to contribute** in the form by selecting areas such as documentation, translations, design, marketing, or community support.
```

2024-09-25 13:22 UTC, RCheesley commented on 2024.md
> +   - Visit the [Mautic Forum](https://forum.mautic.org/) to introduce yourself and engage with the community.
Should we make a sub-section of the Community category specifically for Hacktoberfest, maybe?

2024-09-25 13:22 UTC, RCheesley commented on 2024.md
> +   - Visit the [Mautic Forum](https://forum.mautic.org/) to introduce yourself and engage with the community.
Also wondering if we should have an 'introductions' category perhaps!

2024-09-25 13:23 UTC, RCheesley commented on 2024.md
> +   After contributing to four eligible open-source repositories during Hacktoberfest, you’ll earn a limited-edition Mautic Hacktoberfest digital badges.
```suggestion
   After contributing to four eligible open source repositories during Hacktoberfest, you’ll earn a limited-edition Mautic Hacktoberfest digital badges.
```

2024-09-25 13:35 UTC, fakela commented
> Main thing is not hyphenating open source, and a couple of other suggestions for making it clearer.
> 
> How are we getting them to register their PRs, should we have a table in this doc which shows their name, a link to the contribution and note about what they did, so that it counts as a PR for Hacktoberfest?

I thought we are labelling PRs we want people to work on with hacktoberfest. If yes, do we still need them to add it to a table

2024-09-25 13:42 UTC, RCheesley commented
@fakela the issue is no-code contributors do not have issues/bug reports in GitHub to work from in many cases so it won't be visible in the overall project board, and they don't typically make a PR to contribute (e.g. marketing, design etc). So I was thinking that for those, they could make a PR to this repository to add their no-code contribution, which would mean that PR is then tracked and eligible for Hacktoberfest to count. Unless there's other ways around it, maybe? 

Docs/Dev Docs would not need to do this as they make PRs, but knowledgebase, marketing, design, etc would all need a way for their contribution to be counted.

2024-09-25 13:52 UTC, fakela commented
> @fakela the issue is no-code contributors do not have issues/bug reports in GitHub to work from in many cases so it won't be visible in the overall project board, and they don't typically make a PR to contribute (e.g. marketing, design etc). So I was thinking that for those, they could make a PR to this repository to add their no-code contribution, which would mean that PR is then tracked and eligible for Hacktoberfest to count. Unless there's other ways around it, maybe?
> 
> Docs/Dev Docs would not need to do this as they make PRs, but knowledgebase, marketing, design, etc would all need a way for their contribution to be counted.

 
Oh I get it now. What your suggested should work to track their contributions

2024-09-25 16:03 UTC, favour-chibueze commented
> > @fakela the issue is no-code contributors do not have issues/bug reports in GitHub to work from in many cases so it won't be visible in the overall project board, and they don't typically make a PR to contribute (e.g. marketing, design etc). So I was thinking that for those, they could make a PR to this repository to add their no-code contribution, which would mean that PR is then tracked and eligible for Hacktoberfest to count. Unless there's other ways around it, maybe?
> > 
> > Docs/Dev Docs would not need to do this as they make PRs, but knowledgebase, marketing, design, etc would all need a way for their contribution to be counted.
> 
>  
> Oh I get it now. What your suggested should work to track their contributions 



We can have the no-code contributors create/submit issues themselves on this repository, detailing their planned contributions (e.g., marketing, design work). 

Once the issue is reviewed and accepted, we can add the Hacktoberfest label, assign the issue, and have them make a PR that reflects their completed work. This way, the contributions are verified and tracked properly, ensuring they count for Hacktoberfest while keeping everything organized.

cc: @fakela @RCheesley

2024-09-25 18:43 UTC, favour-chibueze commented on 2024.md
> +   - Visit the [Mautic Forum](https://forum.mautic.org/) to introduce yourself and engage with the community.
Yes, we can do that

2024-09-26 10:20 UTC, RCheesley requested changes
Looks great! A few small additions just to explain how to make a PR to this repo, and adding the table for the activity log.  See what you think!

2024-09-26 10:20 UTC, RCheesley commented on 2024.md
> +   For documentation or translations, submit your work via a pull request on GitHub or follow the submission process on Transifex. Make sure to reference Hacktoberfest in your contribution notes.
```suggestion
For documentation, submit your work via a pull request on GitHub - make sure to reference Hacktoberfest in your contribution notes so that the team know to add the `hacktoberfest-accepted` label. For other tasks like translations or writing on the knowledgebase, follow the submission process on Transifex or the knowledgebase and then follow the steps below to have your contribution validated for Hacktoberfest. 
   
For no-code contributions where there is no pull request to make (e.g. marketing, design etc) we've created this file in this repository where we will maintain an activity log, which will allow you to submit a pull request (so that it counts for Hacktoberfest) each time you complete a task.

To do this, follow these steps:

1. Log in to GitHub with your GitHub account
2. Click the Fork button at the top right
3. Edit the relevant file for the current year, and add your contribution and a link to the issue at the bottom of the list. Follow any instructions that are written as to the formatting to use
4. Click the button to commit your changes, and make a new branch (ideally call it something relevant to this contribution, so you know what each one is)
5. Go back to the [Hacktoberfest no code](https://github.com/mautic/hacktoberfest-no-code) repository
6. Click the button at the top of the page to make a new pull request
7. Add the details about your contribution, and submit the pull request for the team to review
8. Celebrate! 🥳

Please follow this process for each contribution, so that it counts for Hacktoberfest. The team will add the label 'hacktoberfest-accepted' which will allow you to have your contributions counted.
```

2024-09-26 10:20 UTC, RCheesley commented on 2024.md
> +Thank you for being part of the Mautic community and for your contributions to Hacktoberfest 2024. Every contribution helps make Mautic better for users around the world!
```suggestion
Thank you for being part of the Mautic community and for your contributions to Hacktoberfest 2024. Every contribution helps make Mautic better for users around the world!

## 2024 Hacktoberfest no-code contribution activity log

When linking to your contribution, please write a descriptive title and use the full link of the Jira issue, Knowledgebase article, or other reference. For example [Article on how to contribute to the Knowledgebase](https://kb.mautic.org/article/how-to-contribute-to-the-knowledge-base.html).

| Your name | Link to your contribution | Notes |
|-----------|---------------------------|-------|
| Favour Chibueze (@favour-chibueze)         |   #1                         | Initial setup of the Hacktoberfest no-code documentation      |
|           |                           |       |
|           |                           |       |
```

2024-09-28 21:39 UTC, favour-chibueze commented
@RCheesley I think this PR is good to go and can be merged.

cc: @fakela

2024-09-29 20:49 UTC, merged

2024-10-19 06:47 UTC, favour-chibueze commented
@RCheesley the holopin stickers now work. 🎉 
https://github.com/mautic/hacktoberfest-no-code/pull/1#issuecomment-2423620630

2024-10-19 17:57 UTC, RCheesley commented
Yahoo! What did we do wrong?

2024-10-19 19:39 UTC, favour-chibueze commented
> Yahoo! What did we do wrong?

Just added the alias as a label